### ISSUE TITLE
export an instance by default

### ISSUE THREAD

**Issue by timoxley** [kentcdodds/api-check#15]
Current setup requires user to reconfigure apiCheck in every file they use it in. I feel that use-cases will not need such flexibility and a single instance is probably preferable.

I'd like to suggest the default export be an apiCheck instance so it can be used to validate stuff right out of the box.

``` js
var apiCheck = require('api-check') // note no call ()
apiCheck.warn([apiCheck.object], [apiCheck]) // doesn't work, probably should.
```

Note the current setup also necessitates creation of two bindings when using module syntax:

``` js
import APICheck from 'api-check' // can't import + instantiate on one line
const apiCheck = APICheck() // blegh
```

**Comment by kentcdodds** [comment]
You should have a single module that configures your app's instance of `apiCheck` and then require that module throughout your app. Doing that will solve both of those problems.

``` javascript
// myApiCheck.js
import apiCheck from 'api-check';
export default apiCheck({
  prefix: 'my app apiCheck'
});


// some-other-file.js
import myApiCheck from 'myApiCheck';

myApiCheck.warn(myApiCheck.func, [myApiCheck]); // <-- myApiCheck is actually a function :-)
```
