### ISSUE TITLE
Null type

### ISSUE THREAD

**Issue by alismith-dev** [kentcdodds/api-check#16]
It'd be useful to have a `null` type. I'm using apiCheck for HTTP response testing (and it's great, thanks :smile:) and some of my responses can be `null`.

Here's the custom type I'm using at the moment to work around it:

``` javascript
let nullType = (val, name, location) => {
  if (val !== null) return apiCheck.utils.getError(name, location, 'null')
}
```

**Comment by kentcdodds** [comment]
Thanks for posting this issue. It's something I've been meaning to include. I have a few extra types that I think we need that I have in my own project. Like `null`, `emptyObject`, and `range` :-) If you have any other suggestions I'd love that.

**Comment by alismith-dev** [comment]
:+1: for all of those.

The only other thing I thought of was a shortcut for values which can have a type or can be `null`. Maybe `nullable`?

**Comment by kentcdodds** [comment]
You've got everything you asked for and more in [7.1.0](https://github.com/kentcdodds/apiCheck.js/blob/master/CHANGELOG.md#710) :-) still gotta update the docs. But if you have any questions you can consult the tests!

**Comment by kentcdodds** [comment]
Or, feel free to [ask me](https://gitter.im/kentcdodds/apiCheck.js) of course :-)

**Comment by alismith-dev** [comment]
Awesome! Thanks a lot :smile: I'm upgrading now.
