### ISSUE TITLE
apiCheck.js vs. api-check.js

### ISSUE THREAD

**Issue by rmulder** [kentcdodds/api-check#18]
With a recent code update, the name of the distribution JS file was changed from 'apiCheck.js' to 'api-check.js'.

For those of us attempting to update to the newest version of apiCheck - this caused some serious 'consternation' on our part... Please consider updating the documentation and/or the project name itself (kentcdodds/apiCheck.js) - as it's now misleading and can cause some serious hair-pulling to occur before consulting with you about the change...

Thanks!

**Comment by kentcdodds** [comment]
It's been driving me crazy too. Renamed. Sorry about that :-(
