### ISSUE TITLE
Variable number of arguments

### ISSUE THREAD

**Issue by jpretzel** [kentcdodds/api-check#19]
It would be useful to define a check for a variable length of arguments of the same type. A logger function for example could take multiple strings as arguments:

`log('one string')`
`log('two ', 'strings')`

Do you think this will be possible in the near future, or is it already possible and I just don't get it?

**Comment by kentcdodds** [comment]
Hmmm... I'm not sure what you mean. Could you give an example of the kind of API you'd like to see to accomplish this?

**Comment by jpretzel** [comment]
I was thinking about something like this:

``` javascript
/**
 * Simple logger that allows a variable number of arguments to be logged.
 * @param {...string}
 */
function log () {
    apiCheck.warn([apiCheck.string.multiple], arguments);

    // do something
}
```

I hope this makes more sense to you?

**Comment by kentcdodds** [comment]
That makes sense. You could do something like this:

``` javascript
apiCheck.warn([apiCheck.typeOrArrayOfType(apiCheck.string)], arguments);
```

**Comment by jpretzel** [comment]
Works like a charm, thank you for your help!

**Comment by tnrich** [comment]
Hey, I'm just wondering if this is still a part of the api. I'm getting this error:

```
    ac.throw([ac.range, ac.typeOrArrayOfType(ac.string)], arguments);
                           ^
TypeError: undefined is not a function
```

**Comment by tnrich** [comment]
Found it! its now typeOrArrayOf
