### ISSUE TITLE
A way to generate "shapes"/models definition from some other file (json, xml) ?

### ISSUE THREAD

**Issue by fabm22** [kentcdodds/api-check#47]
Hi,

great project. I would like to know if you would be aware of some way to generate the "shapes" of the models from some XML/XSD or simply Json files ...?  From some schema basically ..?

Thanks for your help

**Comment by kentcdodds** [comment]
I'm sure it's possible. Would just require some custom code...

**Comment by fabm22** [comment]
Hi thanks for your answer and sorry for delay.
I would be interested in doing so. Any good pointers for me to where to start ?? 

I would want to use it particurarly with an angular project 

Thanks for your help!

**Comment by kentcdodds** [comment]
Yeah, api-check is totally independent of angular. You could easily generate a shape like so:

``` javascript
var objectOfCheckers = arrayMetaData.reduce(function(obj, metaData) {
  obj[metaData.key] = apiCheck[metaData.type]
  return obj
}, {})
var shape = apiCheck.shape(objectOfCheckers)
```

That's sort of how something might work. Best of luck to you!
