### ISSUE TITLE
Out Of Stack Space error when using IE

### ISSUE THREAD

**Issue by CodeLiftSleep** [kentcdodds/api-check#53]
I am using this together with Formly and while using a UIB-Autocomplete it triggers an Out of Stack Space error in API-check.

Basically what we are doing is this:  We have it set to do an Async Get call where there are more than 2 characters entered in the search box and then that brings back from the Server any matching results.  If you type in a bunch of stuff that doesn't match, once you hit 4 or 5 times and then delete back to the beginning to start over, it throws this error on the first character you type in again and crashes.

No issues on Chrome

From what I've read its related to recursion a lot of time and this is apparently a workaround/fix for it:

```
process.nextTick = (function(){
  var timeouts = []
  // postMessage behaves badly on IE8
  if (window.ActiveXObject || !window.postMessage) {
    return function(fn){
      timeouts.push(fn);
      setTimeout(function(){
        if (timeouts.length) timeouts.shift()();
      }, 0);
    }
  }

  // based on setZeroTimeout by David Baron
  // - http://dbaron.org/log/20100309-faster-timeouts
  var name = 'mocha-zero-timeout'

  window.addEventListener('message', function(e){
    if (e.source == window && e.data == name) {
      if (e.stopPropagation) e.stopPropagation();
      if (timeouts.length) timeouts.shift()();
    }
  }, true);

  return function(fn){
    timeouts.push(fn);
    window.postMessage(name, '*');
  }
})();
```

Fix is from the mocha project
https://github.com/mochajs/mocha/issues/502

**Comment by kentcdodds** [comment]
Interesting workaround. But in reality, you should know that api-check is a development tool and should be disabled in production. Please follow the example here: http://angular-formly.com/#/example/other/production-tips to disable api-check in production.
