### ISSUE TITLE
Make verbose and enabled state global

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/api-check#9]
right now this is a per-instance thing, but it should probably be global.

**Comment by timoxley** [comment]
For regular web `window` is already a garbage pile so do with it what you will, but in node rather than pollute globals I suggest toggling via an env var. If using browserify one can use https://www.npmjs.com/package/envify to bake env vars into a build.

**Comment by kentcdodds** [comment]
Thanks for the feedback @timoxley, but what I mean by this isn't to put it on `window` or the node global, what I mean is I want to be able to do this:

``` javascript
var apiCheck = require('api-check');
var myInstance = apiCheck({/* my options */});

apiCheck.globalConfig.disabled = true;
```

And have all instances of `apiCheck` be disabled. This way I can disable library's instances in production as well.

**Comment by timoxley** [comment]
note that an implementation of this that doesn't use a true global and instead relies on the require cache serving up the same instance is going to be flakey. `require('api-check')` doesn't guarantee the same instance will be returned across your application. Simple case is when there's two different versions of `api-check` installed, but this can even happen for the same version required in multiple locations. The node_modules hierarchy is not necessarily deduped and it's quite possible that multiple copies of the exact same version of `api-check` will be in use, thus setting `apiCheck.globalConfig.disabled` in one location may or may not affect the others, depending on the configuration of packages in `node_modules`.

This fact also affects/invalidates my other request in #15

**Comment by kentcdodds** [comment]
> Simple case is when there's two different versions of api-check installed, but this can even happen for the same version required in multiple locations

This is solved by your dependencies using `peerDependencies` rather than `dependencies`. But because you can't necessarily enforce that yourself, they'll have to expose a way for you to disable their instance `api-check`. Either way, you're at the mercy of the library author to enable you to disable api-check. I don't know of any other solution. Do you have any suggestions?

**Comment by kentcdodds** [comment]
This is now supported in 7.0.0. Simply do:

``` javascript
var apiCheck = require('api-check');
apiCheck.globalConfig.disabled = true;
```

Do this before you create your own instance and all of the apiCheck instances will be created with `noop` checkers.
